[package]
name = "multi_platformer"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
macroquad = "0.4.13"
serde = { version = "1.0.210", features = ["serde_derive"] }
serde-big-array = "0.5.1"
